### ISSUE TITLE
Exception on game startup on nvidia with 555 driver

### ISSUE THREAD

**Issue by reinux** [bryanedds/Nu#823] opened 2024-06-11 01:07 UTC
Exception:
```
System.Exception: Could not create GlRenderer3d due to: Could not create complete shadow texture framebuffer (status: 0; error: NoError).
   at Nu.GlRenderer3d.make(IntPtr glContext, Window window) in /home/rei/source/Nu/Nu/Nu/Render/Renderer3d.fs:line 3008
   at Nu.RendererThread.Run(ImFontAtlasPtr fonts, FSharpOption`1 windowOpt) in /home/rei/source/Nu/Nu/Nu/Render/RendererProcess.fs:line 330
   at <StartupCode$Nu>.$RendererProcess.thread@419-1.Invoke() in /home/rei/source/Nu/Nu/Nu/Render/RendererProcess.fs:line 419
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

I have it printing the output of `CheckFramebufferStatus` and `Gl.GetError` in the exception. My current suspicion, based on the [Khronos documentation](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glCheckFramebufferStatus.xhtml), is that the framebuffer is nonzero -- which is a thing that can happen on Linux because malloc doesn't necessarily zero out memory.

**Comment by bryanedds** [comment] 2024-06-11 02:52
Please also add detail on what you tried as well as on what driver versions it did work on. I'm not sure the current level of detail is enough to be actionable.

**Comment by reinux** [comment] 2024-06-11 06:22
Haven't done much yet beyond just inspecting with breakpoints and reading some docs.

I believe it worked fine on 545 and 550. 555 is the huge stability update though, and the general consensus is that it's a very good one, so unless there's been some kind of regression, I have a feeling it might not be a bug in the driver so much as that it's exposed some obscure problem.

The value of `framebuffer` in `TryCreateShadowBuffers`  appears to be correct (0), but if I let it continue without checking that the buffer is complete, `framebuffer` continues to be 0 in further iterations, which suggests that the buffer is either being discarded or that it isn't actually being produced.

**Comment by bryanedds** [comment] 2024-06-11 06:38
If there's an NVidia support forum, you should also check there. There may be known bugs or regressions about r555 or links about those that can be found there. If you can get forum support for this, it might find discovering root cause more expedient.

>>The value of framebuffer in TryCreateShadowBuffers appears to be correct (0)

Why would that be correct? 0 is the default framebuffer, and if any call to Gl.GenFramebuffer returns 0, then it indicates an error.

**Comment by bryanedds** [comment] 2024-06-11 06:44
Here's one potentially relevant forum thread -

https://forums.developer.nvidia.com/t/555-release-feedback-discussion/293652/5

**Comment by reinux** [comment] 2024-06-11 07:14
Ah, I assumed the first ID would be 0. It starts at 1 on my AMD machine, so yeah, something's up.

I'll take a look through the thread.

**Comment by bryanedds** [comment] 2024-06-11 07:23
I just finished having a look through the thread - there's nothing really specific enough in there to be relevant to this other than the general case that this is a beta driver and there are plenty of regressions and a lot of fix-faileds. But at least it's adjacent to a board you might be able to put up a specific question about potential r555 regressions.

**Comment by reinux** [comment] 2024-07-02 22:53
Issue persists with 555.58, which came out last week. Not a problem for me personally at the moment, as I can work on my laptop.

**Comment by bryanedds** [comment] 2024-07-15 06:44
I'm still tentatively concluding this is an environment issue on a specific machine, specifically the combination of this new driver set and Wayland and perhaps some other config.

**Comment by bryanedds** [comment] 2024-07-25 23:09
Apparently r560 also has the same issue -

https://www.reddit.com/r/linux_gaming/comments/1eav0k1/do_not_install_nvidia_560_drivers_yet/

...and as I suspected about r555, it appears to be Wayland-related as well.

![image](https://github.com/user-attachments/assets/cf41db62-55cc-4b63-bc3d-bc8a4bd2a5fd)

While some might say that Wayland is inevitable, I would say that our official support for it is not.

**Comment by avandolder** [comment] 2024-08-04 18:28
I'm running into the same exception using Mesa 24.1.4 - given I'm also running Wayland it appears to be more an issue with that than Nvidia.

**Comment by bryanedds** [comment] 2024-08-04 18:31
@avandolder - Thanks for this report! It helps to bolster my current suspicion with respect to Wayland.

**Comment by avandolder** [comment] 2024-08-04 18:47
I will note that it seems to run fine under gamescope - that might be a workaround for anyone else who runs into this.

**Comment by bryanedds** [comment] 2024-08-04 19:57
If I were a betting man, I would be it has something to do with how Wayland interprets SDL's OpenGL initialization path. I understand there was at some point some major confusion about whether Wayland actually supports vanilla OpenGL -

https://unix.stackexchange.com/questions/511134/why-wayland-is-using-opengl-es-instead-of-opengl

**Comment by bryanedds** [comment] 2024-08-20 18:15
Not sure if it's too late to test this, but a recent fix that applies glFinish before swapping may address this issue out of the box.

**Comment by bryanedds** [comment] 2024-08-22 03:58
Closing due to likely env. issues.

**Comment by bryanedds** [comment] 2024-08-27 00:33
This was reopened because there ended up being an obscure environment issue that we wanted to document here in case others run into it. However, that can still be done even if the issue is closed.

**Closed by bryanedds** 2024-08-27 00:33 UTC
Labels: linux, investigation
