### ISSUE TITLE
Texture format

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#237] opened 2019-06-28 08:37 UTC
Why Nu allows only 32bbpArgb image format?

https://github.com/bryanedds/Nu/blob/5b40993e07ac884ddd8a613e009ba3afdda30ca5/Nu/Nu/Metadata.fs#L53-L58

**Comment by bryanedds** [comment] 2019-06-28 21:29
If I remember correctly, Nu.Pipe imports other image formats then always outputs a 32-bit ARGB. So since that's the only format that Nu.Pipe outputs, there's no need for it to worry about other formats at run-time.

Was this causing you some sort of specific issue that I can look into? If not, I'll go ahead and close this issue.

**Comment by nanodesu88** [comment] 2019-06-29 08:31
When i try loading a different than 32bbpargb images Nu throws an error. 
To fix it i had to prepare images, convert files pixel format manually

**Comment by bryanedds** [comment] 2019-06-29 16:24
Okay, that's an issue then if the importer is not converting everything to argb32.

I'll try reproducing the issue on my side.

**Comment by bryanedds** [comment] 2019-06-29 16:50
Okay, I delved back into the code and it seems I had a false memory. Apparently Nu.Pipe merely copies the image files rather than normalizing it to its one expected format. Now Nu handles all pixel formats supported by System.Drawing.

Please git update Nu and close this if the problem is solved on your end. Thanks!

**Comment by bryanedds** [comment] 2019-06-30 01:51
I'll just go ahead and close

**Closed by bryanedds** 2019-06-30 01:51 UTC
